name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers:
          - 1.17.8-bullseye
          - 1.18.0-bullseye
          - 1.19.2-bullseye
    runs-on: ubuntu-20.04
    container: golang:${{matrix.containers}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test -race -timeout=60s ./...
